name: Auto approve

on:
  workflow_dispatch:
    inputs: 
      pullRequestNumber:
        description: Pull request number to auto-approve
        required: false

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v4
      with:
        pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
        personal_token: ${{ secrets.GH_PERSONAL_TOKEN }}
        github-token: ${{ secrets.SOME_USERS_PAT }}


    #     steps:
    # - name: Approve Pull Request
    #   uses: juliangruber/approve-pull-request-action@v2
    #   with:
    #     github-token:  ${{ secrets.GH_PERSONAL_TOKEN }}
    #     # personal_token: ${{ secrets.GH_PERSONAL_TOKEN }}
    #     number: ${{ github.event.inputs.pullRequestNumber }}
