name: Auto approve
on:
  pull_request:
    branches:
    - master
    types: [opened] # probably the only one you need


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
