name: Issue Commenter

on:
  issues:
    types: [opened]

jobs:
  comment-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pandas
        run: python -m pip install pandas

      - name: Execute Python script on issue content
        id: process_issue
        env:
          ISSUE_TITLE: ${{github.event.issue.title}}
          ISSUE_BODY: ${{github.event.issue.body}}
          ISSUE_NUMBER: ${{github.event.issue.number}}
        run: |
            python .github/scripts/process_issue.py >> pr/output_$ISSUE_NUMBER.json


      # - name: see output
      #   id: see_output
      #   run: |
      #       cat output.json
      #       echo ${{ steps.process_issue.outputs.content }}
      #       echo $other_content
      - name: Create pr
        uses: peter-evans/create-pull-request@v6

      - name: Comment on the issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path');
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const body = fs.readFileSync('pr/output_' + issueNumber + '.json', 'utf8');
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body
            });
