name: Issue Commenter

on:
  issues:
    types: [opened]

jobs:
  comment-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Execute Python script on issue content
        id: process_issue
        env:
          ISSUE_TITLE: ${{github.event.issue.title}}
          ISSUE_BODY: ${{github.event.issue.body}}
        run: |
          echo "file_content<<EOF" >> $GITHUB_ENV
          python .github/scripts/process_issue.py >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV


      - name: Comment on the issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = process.env.file_content;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: message,
            })
