name: Issue Commenter

on:
  issues:
    types: [opened]

jobs:
  comment-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pandas
        run: python -m pip install pandas

      - name: Execute Python script on issue content
        id: process_issue
        env:
          ISSUE_TITLE: ${{github.event.issue.title}}
          ISSUE_BODY: ${{github.event.issue.body}}
        run: |
            python .github/scripts/process_issue.py >> output.json
            content=$(cat output.json)
            echo "::set-output name=content::$content"
            echo "other_content<<EOF" >> $GITHUB_ENV
            cat output.json >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV


      # - name: see output
      #   id: see_output
      #   run: |
      #       cat output.json
      #       echo ${{ steps.process_issue.outputs.content }}
      #       echo $other_content


      - name: Comment on the issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path');
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const body = fs.readFileSync('output.json', 'utf8');
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body
            });
